export { meta } from '~/pages/events/get/meta'
export { loader } from '~/pages/events/get/loader'
export { action } from '~/pages/events/get/action'
export { GetEvent as default } from '~/pages/events/get/get-event'
export { CatchBoundary } from '~/pages/events/get/catch-boundary'
