export { meta } from '~/pages/events/event/meta'
export { loader } from '~/pages/events/event/loader'
export { action } from '~/pages/events/event/action'
export { Event as default } from '~/pages/events/event/event'
export { CatchBoundary } from '~/pages/events/event/catch-boundary'
