on:
  pull_request:
    types:
      - closed

jobs:
  merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
  remove:
    runs-on: ubuntu-latest
    environment: development
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-north-1
      AWS_REGION: eu-north-1
      PR_NAME: pr-${{ github.event.pull_request.id }}
      SST: npx @serverless-stack/cli@1.17.1 --yes
    steps:
      #      - uses: actions/checkout@v3
      #      - name: Install
      #        run: yarn install --immutable --immutable-cache --check-cache
      - name: Remove common sst secrets
        run: |
          $SST secrets --stage $PR_NAME remove AUTH_CLIENT_SECRET ${{ secrets.AUTH_CLIENT_SECRET }}
          $SST secrets --stage $PR_NAME remove REGISTER_SECRET ${{ secrets.REGISTER_SECRET }}
      - name: Remove infra
        run: |
          $SST remove --stage $PR_NAME