# This is a basic workflow to help you get started with Actions

name: Production

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_DEFAULT_REGION: eu-north-1
      AWS_REGION: eu-north-1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: corepack enable
      - name: Install
        run: yarn install --immutable
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/GitHubActionRole
          aws-region: us-east-1
          role-duration-seconds: 2500
      - name: Set sst secrets
        run: |
          yarn sst secrets --stage production set AUTH_CLIENT_SECRET ${{ secrets.AUTH_CLIENT_SECRET }}
          yarn sst secrets --stage production set REGISTER_SECRET ${{ secrets.REGISTER_SECRET }}
          yarn sst secrets --stage production set COOKIE_SECRET ${{ secrets.COOKIE_SECRET }}
      - name: Build and deploy
        run: |
          yarn sst types --stage production
          yarn build
          yarn sst deploy --stage production